name: HopeCraft
main: org.hopestudio.hopeCraft.HopeCraft
version: 1.5.0
api-version: "1.21"
commands:
  hopecraft:
    description: 打开HopeCraft主菜单
    usage: /hopecraft
  skull:
    description: 获取玩家头颅
    usage: /skull [玩家名]