name: HopeCraft
main: org.hopestudio.hopeCraft.HopeCraft
version: 1.6.3
api-version: "1.21"
commands:
  hopecraft:
    description: 打开HopeCraft主菜单
    usage: /hopecraft
  skull:
    description: 获取玩家头颅
    usage: /skull [玩家名]
permissions:
  hopecraft.admin:
    description: HopeCraft管理员权限，可以控制是否监听Shift+F按键
    default: op
